swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /user:
    x-swagger-router-controller: users
    get:
      operationId: get
      description: Trả về danh sách user
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Users"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
            
    post:
      operationId: post
      description: Thêm 1 user mới
      parameters:
        - name: data
          in: body
          required: true
          schema: 
            $ref: "#/definitions/User"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/User"
  /user/{id}:
    x-swagger-router-controller: users
    get:
      operationId: getOne
      description: Trả về danh sách user
      parameters:
        - name: id
          type: number
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Users"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      
    
# complex objects have schema definitions
definitions:
  User:
    type: object
    properties:
      name:
        type: string
        description: Tên của thành viên
      gender:
        type: boolean
        description: Giới tính
      age:
        type: number
        description: Tuổi
  Users:
    properties:
      users:
        type: array
        items:
          type: object
          properties:
            name:
              type: string
            gender:
              type: boolean
            age:
              type: number
    required:
      - users
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
